import { createClient } from "@/lib/supabase/server"
import { chooseTutorStudent, getTutorGuardian, getTutorStudentContacts, getTutorStudents } from "@/app/tutor/data"
import { StudentContext, StudentSelector } from "@/components/tutor/student-selector"
import { TutorNavigation } from "@/components/tutor/tutor-navigation"

export default async function TutorInformationPage({ searchParams }: { searchParams: Promise<{ student?: string }> }) {
  const supabase = await createClient(); const { students, error } = await getTutorStudents(supabase); const { student } = await searchParams; const selected = chooseTutorStudent(students, student); const [{ guardian }, contactsResult] = await Promise.all([getTutorGuardian(supabase), selected ? getTutorStudentContacts(supabase, selected.id) : Promise.resolve({ contacts: [], error: false })])
  return <main className="mx-auto min-h-dvh max-w-5xl space-y-6 p-5 sm:p-8"><TutorNavigation current="info" />{error || !selected ? <p className="text-sm text-muted-foreground">No tienes alumnos autorizados.</p> : <><header className="space-y-3"><StudentContext student={selected} /><StudentSelector students={students} selectedId={selected.id} hrefBase="/tutor/informacion" /></header><section className="space-y-4 border-y border-border bg-white px-4 py-5 sm:rounded-xl sm:border"><h1 className="text-base font-semibold">Tus datos</h1><dl className="grid gap-4 sm:grid-cols-3"><Metric label="Nombre" value={guardian?.full_name ?? "Sin dato"} /><Metric label="WhatsApp / teléfono" value={guardian?.phone ?? "Sin dato"} /><Metric label="Correo" value={guardian?.email ?? "Sin dato"} /></dl></section><section className="space-y-4"><h2 className="text-base font-semibold">Contactos relacionados</h2><div className="divide-y divide-border border-y border-border bg-white md:rounded-xl md:border">{contactsResult.contacts.length ? contactsResult.contacts.map((contact, index) => { const data = Array.isArray(contact.guardians) ? contact.guardians[0] : contact.guardians; return <div key={`${contact.relationship}-${index}`} className="px-4 py-4 text-sm"><p className="font-medium">{data?.full_name}</p><p className="mt-1 text-muted-foreground">{contact.relationship} · {data?.phone ?? "Sin teléfono"}</p></div> }) : <p className="px-4 py-5 text-sm text-muted-foreground">No hay otros contactos disponibles para mostrar.</p>}</div><p className="text-sm text-muted-foreground">¿Necesitas actualizar algún dato? Solicita el cambio directamente en Administración.</p></section></>}</main>
}
function Metric({ label, value }: { label: string; value: string }) { return <div><dt className="text-sm text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div> }
