"use client"

import { Eye, EyeOff, LoaderCircle } from "lucide-react"
import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { createClient } from "@/lib/supabase/client"
import { getSiteUrl } from "@/lib/site/url"

export function FamilyOnboardingForm({ token, students }: { token: string; students: Array<{ id: string; name: string }> }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [visible, setVisible] = useState(false); const [confirmationVisible, setConfirmationVisible] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(null); if (!/^\S+@\S+\.\S+$/.test(email.trim())) return setError("Captura un correo válido."); if (password.length < 8) return setError("La contraseña debe tener al menos 8 caracteres."); if (password !== confirmation) return setError("Las contraseñas no coinciden."); setPending(true); const { error: signupError } = await createClient().auth.signUp({ email: email.trim(), password, options: { emailRedirectTo: `${getSiteUrl()}/auth/familia/callback?token=${encodeURIComponent(token)}` } }); setPending(false); if (signupError) return setError("No pudimos registrar ese correo. Verifica los datos o intenta con otro."); setDone(true) }
  if (done) return <div className="rounded-xl border border-border bg-white p-5"><h2 className="font-semibold">Revisa tu correo para confirmar tu cuenta.</h2><p className="mt-2 text-sm text-muted-foreground">Después de confirmar, tu acceso quedará listo y podrás entrar a REAL.</p></div>
  return <form noValidate onSubmit={submit} className="space-y-5 rounded-xl border border-border bg-white p-5"><div><p className="text-sm font-medium">Alumnos autorizados</p><ul className="mt-2 space-y-1 text-sm text-muted-foreground">{students.map((student) => <li key={student.id}>{student.name}</li>)}</ul></div><Field label="Correo"><Input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} /></Field><Field label="Contraseña"><div className="relative"><Input type={visible ? "text" : "password"} autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} className="pr-11" /><Button type="button" variant="ghost" size="icon" className="absolute right-1 top-1/2 -translate-y-1/2" aria-label={visible ? "Ocultar contraseña" : "Mostrar contraseña"} onClick={() => setVisible(!visible)}>{visible ? <EyeOff /> : <Eye />}</Button></div></Field><Field label="Confirmar contraseña"><div className="relative"><Input type={confirmationVisible ? "text" : "password"} autoComplete="new-password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="pr-11" /><Button type="button" variant="ghost" size="icon" className="absolute right-1 top-1/2 -translate-y-1/2" aria-label={confirmationVisible ? "Ocultar confirmación de contraseña" : "Mostrar confirmación de contraseña"} onClick={() => setConfirmationVisible(!confirmationVisible)}>{confirmationVisible ? <EyeOff /> : <Eye />}</Button></div></Field>{error && <p className="text-sm text-destructive" role="alert">{error}</p>}<Button className="h-11 w-full" disabled={pending}>{pending && <LoaderCircle className="animate-spin" />} {pending ? "Creando acceso…" : "Crear acceso"}</Button></form>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <Label className="grid gap-2 text-sm font-medium"><span>{label}</span>{children}</Label> }
