'use client'

import { Eye, EyeOff, LoaderCircle } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { useState, useTransition } from 'react'
import { claimStaffInvitationEmail } from '@/app/admin/usuarios/actions'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { createClient } from '@/lib/supabase/client'
import { getSiteUrl } from '@/lib/site/url'

export function StaffOnboardingForm({ token, initialEmail }: { token: string; initialEmail: string }) {
  const router = useRouter()
  const [email, setEmail] = useState(initialEmail); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [passwordVisible, setPasswordVisible] = useState(false); const [confirmationVisible, setConfirmationVisible] = useState(false); const [error, setError] = useState<string | null>(null); const [done, setDone] = useState(false); const [resent, setResent] = useState(false); const [mode, setMode] = useState<'signup' | 'login'>('signup'); const [isPending, startTransition] = useTransition()
  function submit(event: React.FormEvent) { event.preventDefault(); setError(null); console.info('[staff onboarding] submit:start', { hasToken: Boolean(token), hasEmail: Boolean(email.trim()), mode }); if (!token) return setError('El enlace de invitación no es válido.'); if (!email.trim()) return setError('Indica tu correo.'); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) return setError('Captura un correo válido.'); if (password.length < 8) return setError('La contraseña debe tener al menos 8 caracteres.'); if (mode === 'signup' && password !== confirmation) return setError('Las contraseñas no coinciden.'); startTransition(async () => { try { const client = createClient(); const tokenHash = await hashToken(token); const claimed = await claimStaffInvitationEmail(tokenHash, email); if (!claimed.ok) return setError(claimed.message); if (mode === 'login') { const { error: loginError } = await client.auth.signInWithPassword({ email: email.trim(), password }); if (loginError) return setError('El correo o la contraseña no son correctos.'); const { error: completionError } = await client.rpc('complete_staff_onboarding', { p_token_hash: tokenHash }); if (completionError) return setError('No pudimos completar tu acceso administrativo. La invitación puede haber expirado o ya no estar disponible.'); router.push('/login'); return } console.info('[staff onboarding] claim:result', { ok: claimed.ok }); console.info('[staff onboarding] signup:start', { hasEmail: Boolean(email.trim()) }); const { error: signUpError } = await client.auth.signUp({ email: email.trim(), password, options: { emailRedirectTo: `${getSiteUrl()}/auth/staff/callback?token=${encodeURIComponent(token)}` } }); console.info('[staff onboarding] signup:result', { ok: !signUpError, error: signUpError?.name ?? null }); if (signUpError) return setError('No pudimos registrar ese correo. Verifica los datos o intenta con otro.'); setDone(true) } catch (caughtError) { console.error('[staff onboarding] submit:error', caughtError instanceof Error ? { name: caughtError.name, message: caughtError.message } : { valueType: typeof caughtError }); setError('No pudimos completar el registro. Intenta de nuevo.') } }) }
  async function resend() { setError(null); const { error: resendError } = await createClient().auth.resend({ type: 'signup', email: email.trim(), options: { emailRedirectTo: `${getSiteUrl()}/auth/staff/callback?token=${encodeURIComponent(token)}` } }); if (resendError) return setError('No pudimos reenviar el correo. Intenta de nuevo más tarde.'); setResent(true) }
  if (done) return <div className="rounded-xl border border-border bg-white p-5"><h2 className="font-semibold">Revisa tu correo para confirmar tu cuenta.</h2><p className="mt-2 text-sm text-muted-foreground">Después de confirmar, tu acceso quedará listo para iniciar sesión en REAL.</p><Button type="button" variant="outline" className="mt-5 w-full" onClick={resend}>{resent ? 'Correo reenviado' : 'Reenviar correo de confirmación'}</Button>{error && <p className="mt-3 text-sm text-destructive" role="alert">{error}</p>}</div>
  return <form noValidate onSubmit={submit} className="space-y-5"><Field label="Correo"><Input type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} className="h-12" /></Field><PasswordField label="Contraseña" value={password} onChange={setPassword} visible={passwordVisible} onToggle={() => setPasswordVisible((visible) => !visible)} />{mode === 'signup' && <PasswordField label="Confirmar contraseña" value={confirmation} onChange={setConfirmation} visible={confirmationVisible} onToggle={() => setConfirmationVisible((visible) => !visible)} />}{error && <p className="rounded-lg border border-destructive/20 bg-destructive/5 px-3 py-2 text-sm text-destructive" role="alert">{error}</p>}<Button type="submit" className="h-12 w-full" disabled={isPending}>{isPending && <LoaderCircle className="animate-spin" />}{isPending ? (mode === 'login' ? 'Iniciando sesión…' : 'Creando acceso…') : (mode === 'login' ? 'Iniciar sesión y continuar' : 'Crear acceso')}</Button><button type="button" className="w-full text-center text-sm font-medium text-muted-foreground underline-offset-4 hover:text-foreground hover:underline" onClick={() => { setMode(mode === 'signup' ? 'login' : 'signup'); setConfirmation(''); setError(null) }}>{mode === 'signup' ? 'Ya tengo una cuenta' : 'Crear una cuenta nueva'}</button></form>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <Label className="grid gap-2 text-sm font-medium"><span>{label}</span>{children}</Label> }
function PasswordField({ label, value, onChange, visible, onToggle }: { label: string; value: string; onChange: (value: string) => void; visible: boolean; onToggle: () => void }) { return <Field label={label}><div className="relative"><Input type={visible ? 'text' : 'password'} autoComplete="new-password" value={value} onChange={(event) => onChange(event.target.value)} required className="h-12 pr-12" /><Button type="button" variant="ghost" size="icon" aria-label={visible ? `Ocultar ${label.toLowerCase()}` : `Mostrar ${label.toLowerCase()}`} className="absolute right-1.5 top-1/2 size-9 -translate-y-1/2 text-muted-foreground hover:text-foreground" onClick={onToggle}>{visible ? <EyeOff /> : <Eye />}</Button></div></Field> }
async function hashToken(value: string) { const bytes = new TextEncoder().encode(value); const digest = await crypto.subtle.digest('SHA-256', bytes); return Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, '0')).join('') }
