import { formatCurrency, isChargeVisibleInCycle } from "@/lib/admin/student-account"
import type { TutorAccount } from "@/app/tutor/data"

export function TutorFinance({ account }: { account: TutorAccount }) {
  const charges = account.charges.filter((charge) => isChargeVisibleInCycle(charge))
  const status = Number(account.summary.overdueTotal) > 0 ? "Vencido" : Number(account.summary.outstandingTotal) > 0 ? "Pendiente" : "Al corriente"
  return <div className="space-y-7"><section className="border-y border-border bg-white px-4 py-5 sm:rounded-xl sm:border"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-muted-foreground">Saldo actual</p><p className="mt-1 text-3xl font-semibold tabular-nums">{formatCurrency(account.summary.outstandingTotal)}</p></div><p className={status === "Vencido" ? "text-sm font-medium text-destructive" : "text-sm font-medium"}>{status}</p></div>{status === "Al corriente" && <p className="mt-3 text-sm text-muted-foreground">Estás al corriente con tus pagos.</p>}</section><section><h2 className="text-base font-semibold">Estado de cuenta</h2>{charges.length ? <div className="mt-4 divide-y divide-border border-y border-border bg-white md:overflow-hidden md:rounded-xl md:border"><div className="hidden grid-cols-5 gap-2 border-b border-border bg-muted/50 px-4 py-3 text-xs text-muted-foreground md:grid"><span>Periodo</span><span className="text-right">Importe</span><span className="text-right">Aplicado</span><span className="text-right">Saldo</span><span className="text-right">Estado</span></div>{charges.map((charge) => <div key={charge.id} className="grid gap-3 px-4 py-4 text-sm md:grid-cols-5 md:items-center md:gap-2 md:py-3"><div><p className="font-medium">{periodLabel(charge.coverageYear, charge.coverageMonth)}</p><p className="text-xs text-muted-foreground">{charge.conceptName}</p></div><span className="md:text-right">{formatCurrency(charge.effectiveAmount)}</span><span className="md:text-right">{formatCurrency(charge.totalApplied)}</span><span className={charge.isOverdue ? "font-medium text-destructive md:text-right" : "md:text-right"}>{formatCurrency(charge.outstandingAmount)}</span><span className={charge.isPaid ? "text-emerald-700 md:text-right" : charge.isOverdue ? "text-destructive md:text-right" : "md:text-right"}>{charge.isPaid ? "Pagado" : charge.isOverdue ? "Vencido" : "Pendiente"}</span></div>)}</div> : <p className="mt-4 border-y border-border py-5 text-sm text-muted-foreground">No hay cargos financieros registrados.</p>}</section><section><h2 className="text-base font-semibold">Historial de pagos</h2>{account.payments.length ? <div className="mt-4 divide-y divide-border border-y border-border bg-white md:rounded-xl md:border">{account.payments.map((payment) => <div key={payment.id} className="grid gap-1 px-4 py-4 text-sm sm:grid-cols-3 sm:gap-4"><span>{formatDate(payment.receivedAt)}</span><span className="font-medium tabular-nums">{formatCurrency(payment.amount)}</span><span className="text-muted-foreground">{payment.methodName} · {payment.receivedByName}</span></div>)}</div> : <p className="mt-4 border-y border-border py-5 text-sm text-muted-foreground">No hay pagos registrados.</p>}</section></div>
}
function periodLabel(year: number | null, month: number | null) { if (!year || !month) return "Sin periodo"; return new Intl.DateTimeFormat("es-MX", { month: "long", year: "numeric" }).format(new Date(year, month - 1, 1)) }
function formatDate(value: string) { return new Intl.DateTimeFormat("es-MX", { dateStyle: "medium" }).format(new Date(value)) }
